name: Rust

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os-name: macOS-x86_64
            runs-on: macOS-13
            target: x86_64-apple-darwin
          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
          - os-name: windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
          - os-name: windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "test"
          target: ${{ matrix.platform.target }}

    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v4
    #     with:
    #       submodules: true
    #   - name: Build
    #     run: cargo build --verbose
    #   - name: Run tests
    #     run: cargo test --verbose
