name: Rust

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - target: "x86_64-unknown-linux-musl"
            image_tag: "x86_64-musl"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v4
    #     with:
    #       submodules: true
    #   - name: Build
    #     run: cargo build --verbose
    #   - name: Run tests
    #     run: cargo test --verbose
